# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scriptsMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scriptsMenu(object):
    def setupUi(self, scriptsMenu):
        scriptsMenu.setObjectName("scriptsMenu")
        scriptsMenu.resize(400, 500)
        scriptsMenu.setMinimumSize(QtCore.QSize(400, 500))
        scriptsMenu.setMaximumSize(QtCore.QSize(400, 500))
        self.verticalLayoutWidget = QtWidgets.QWidget(scriptsMenu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 341, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.autoModeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.autoModeButton.setObjectName("autoModeButton")
        self.verticalLayout.addWidget(self.autoModeButton)
        self.downloadProfilesButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.downloadProfilesButton.setObjectName("downloadProfilesButton")
        self.verticalLayout.addWidget(self.downloadProfilesButton)
        self.findNewAccountsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.findNewAccountsButton.setObjectName("findNewAccountsButton")
        self.verticalLayout.addWidget(self.findNewAccountsButton)
        self.createRatingsFileButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.createRatingsFileButton.setObjectName("createRatingsFileButton")
        self.verticalLayout.addWidget(self.createRatingsFileButton)
        self.cacheResetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cacheResetButton.setObjectName("cacheResetButton")
        self.verticalLayout.addWidget(self.cacheResetButton)
        self.fileRepairButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.fileRepairButton.setObjectName("fileRepairButton")
        self.verticalLayout.addWidget(self.fileRepairButton)
        self.backButton = QtWidgets.QPushButton(scriptsMenu)
        self.backButton.setGeometry(QtCore.QRect(30, 420, 81, 31))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(scriptsMenu)
        QtCore.QMetaObject.connectSlotsByName(scriptsMenu)

    def retranslateUi(self, scriptsMenu):
        _translate = QtCore.QCoreApplication.translate
        scriptsMenu.setWindowTitle(_translate("scriptsMenu", "Form"))
        self.autoModeButton.setText(_translate("scriptsMenu", "Автоматический режим"))
        self.downloadProfilesButton.setText(_translate("scriptsMenu", "Скачивание найденных профилей"))
        self.findNewAccountsButton.setText(_translate("scriptsMenu", "Поиск новых аккаунтов"))
        self.createRatingsFileButton.setText(_translate("scriptsMenu", "Создание файлов с оценками"))
        self.cacheResetButton.setText(_translate("scriptsMenu", "Сброс кэша"))
        self.fileRepairButton.setText(_translate("scriptsMenu", "Починка файлов"))
        self.backButton.setText(_translate("scriptsMenu", "Назад"))
